name: Compile and deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
  - cron: "0 10 * * *" # At 10:00 UTC every day

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:

    runs-on: ubuntu-latest
    environment: Deployment env
    
    steps:
    - uses: actions/checkout@v4
    
    
    - name: Get new uiua
      run: cargo update
    - name: Build wawa
      run: cargo build --verbose
    - name: Set up ssh
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "${{ secrets.DESTHOST }}" > ~/.ssh/known_hosts

    - name: Temporarily stop daemon in server
      run: ssh ${{ secrets.WAWASRV }} "systemctl stop wawa"
    - name: Transfer file
      run: scp target/release/wawa ${{ secrets.WAWASRV }}:${{ secrets.WAWABINPATH }}
    - name: Re-engage daemon
      run: ssh ${{ secrets.WAWASRV }} "systemctl start wawa"
