name: Compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
  - cron: "0 10 * * *" # At 10:00 UTC every day

env:
  CARGO_TERM_COLOR: always
  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Deployment env
    outputs:
        should-deploy: ${{ steps.should-deploy-step.outputs.SHOULDDEPLOY }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Get new uiua
      run: cargo update 2> updatelog
    - name: Record SHOULDDEPLOY envvar
      id: should-deploy-step
      run: |
        grep 'Updating uiua' updatelog && echo "SHOULDDEPLOY=yes" >> $GITHUB_OUTPUT || echo "SHOULDDEPLOY=no" >> $GITHUB_OUTPUT
        cat Cargo.lock | grep -3 uiua 
    - name: Build wawa
      if: ${{ steps.should-deploy-step.outputs.SHOULDDEPLOY == 'yes' }}
      run: cargo build --verbose --release
    - name: Upload artifact for sending
      if: ${{ steps.should-deploy-step.outputs.SHOULDDEPLOY == 'yes' }}
      uses: actions/upload-artifact@v4
      with:
        name: wawa-binary-artifact
        path: target/release/wawa

  deploy: 
    needs: build

    runs-on: ubuntu-latest
    environment: Deployment env

    if: ${{ needs.build.outputs.should-deploy == 'yes' }}
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: wawa-binary-artifact

    - name: Set up ssh
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "${{ secrets.DESTHOST }}" > ~/.ssh/known_hosts
    - name: Temporarily stop daemon in server
      run: ssh ${{ secrets.WAWASRV }} "systemctl stop wawa"
    - name: Transfer file
      run: scp wawa ${{ secrets.WAWASRV }}:${{ secrets.WAWABINPATH }}
    - name: Re-engage daemon
      run: ssh ${{ secrets.WAWASRV }} "systemctl start wawa"
    - name: Log the occurance
      run: ssh ${{ secrets.WAWASRV }} "date >> update_times"
